version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  springboot-app:
    image: ${DOCKER_USER}/projetdevops:${IMAGE_TAG}
    container_name: springboot-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "8081:8080"

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:mysql://mysql-db:3306/foyer
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: root
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "8082:8081"

volumes:
  mysql_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  nexus_data:
